version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "@types/vscode"
    groups:
      npm-all:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
    open-pull-requests-limit: 1
    groups:
      actions-all:
        patterns:
          - "*"
    labels:
      - dependencies
